version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:2023.02.1

    working_directory: /usr/src/app

    steps:
      - checkout

      # Install Node.js
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # Install npm
      - run:
          name: Install npm
          command: sudo apt-get install -y npm

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Start the application
      - run:
          name: Start Application
          command: npm start

      # Wait for the application to start (adjust sleep time as needed)
      - run:
          name: Wait for Application to Start
          command: sleep 10

      # Test that the application responds
      - run:
          name: Test Application
          command: curl -s http://localhost:8080
          when: always
